### ISSUE TITLE
Do not hide input labels when the inputs are unfocused

### ISSUE THREAD

**Issue by gardenerik** [FMFI-UK-1-AIN-412/resolution-editor#4]
It is painful to select anything in the input fields as they move all the time.

![Peek 2023-05-10 10-11](https://github.com/FMFI-UK-1-AIN-412/resolution-editor/assets/11409143/006e1802-dc0a-44d7-83ad-367a565b1c15)

**Comment by crnkjck** [comment]
Fixed by 43e97d272fd5d7fcd0325f3dd7e7db2b5a16300c
